--- # Copy files from base(server) to nodes

- name : Copy files from base machine to the nodes
  hosts: all
  become: true
  tasks:
   - name: Tasks for copy file from base machine to nodes using playbook
     copy:
       src: /home/ansiadmin/ymlscripts/anilw.txt
       dest: /home/ansiadmin 
       mode: 0600
       owner: anilkumar
