--- #This playbook is for install httpd and start the httpd service

- name: Host names for instll httpd
  hosts: all
  become: true
  tasks:
   - name: Install httpd in all nodes with playbook
     yum:
      name: httpd
      state: installed
   
   - name: Start the httpd service with playbook
     service:
      name: httpd
      state: started     
